# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.synced_folder "../base_project", "/tmp/base_project"
  config.vm.provision :shell, :path => "../install_database.sh", :privileged => false
  config.vm.provision :shell, :path => "../install_app.sh", :privileged => false
  config.vm.network :forwarded_port, host: 4567, guest: 80
end

