# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$setup_script = <<SCRIPT
#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y postgresql

sudo -u postgres createdb mydb
sudo -u postgres createuser myuser -ws
sudo -u postgres psql -U postgres -d postgres -c "alter user myuser with password 'password';"

cp -r /tmp/base_project .

cd base_project
. install.sh
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.synced_folder "../base_project", "/tmp/base_project"

  config.vm.provision :shell, :inline => $setup_script, :privileged => false
  config.vm.network :forwarded_port, host: 4567, guest: 80
end

